export type TIME_SERIES = {
  INTRADAY: 'TIME_SERIES_INTRADAY';
  DAILY: 'TIME_SERIES_DAILY';
  DAILY_ADJUSTED: 'TIME_SERIES_DAILY_ADJUSTED';
  WEEKLY: 'TIME_SERIES_WEEKLY';
  WEEKLY_ADJUSTED: 'TIME_SERIES_WEEKLY_ADJUSTED';
  MONTHLY: 'TIME_SERIES_MONTHLY';
  MONTHLY_ADJUSTED: 'TIME_SERIES_MONTHLY_ADJUSTED';
};

export type COMPANY_PROFILE = {
  OVERVIEW: 'OVERVIEW';
  PROFILE: 'ETF_PROFILE';
  DIVIDENDS: 'DIVIDENDS';
  SPLITS: 'SPLITS';
  EARNINGS: 'EARNINGS';
  INCOME_STATEMENT: 'INCOME_STATEMENT';
  BALANCE_SHEET: 'BALANCE_SHEET';
  CASH_FLOW: 'CASH_FLOW';
  LISTING_STATUS: 'LISTING_STATUS';
  EARNINGS_CALENDAR: 'EARNINGS_CALENDAR';
  IPO_CALENDAR: 'IPO_CALENDAR';
};
